AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Time Tracker
Resources:
  TTTGetScheule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        GetSchedule:
          Type: Api
          Properties:
            Path: /schedules
            Method: GET